---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[megacli]
